# Use root/example as user/password credentials
version: '3'

services:

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Jul1ana!
      MYSQL_DATABASE: alfime2
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1g
        reservations:
          cpus: '0.25'
          memory: 256m
    volumes:
      - alfime-db:/var/lib/mysql

volumes:
  alfime-db:

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080